<!DOCTYPE html>
<html lang="id">
<head>
  <meta charset="UTF-8">
  <title>Cetak Laporan Penyewaan</title>
  <link rel="stylesheet" href="{{ asset('css/admin-laporan-cetak.css') }}">
</head>

<style>
  /* =====================================
   LAPORAN PENYEWAAN MOBIL (PRINT)
===================================== */

@page {
  size: A4 portrait;
  margin: 25mm 20mm 25mm 20mm;
}

body {
  font-family: 'Poppins', sans-serif;
  margin: 0;
  background: #fff;
  color: #222;
}

/* ===== HEADER ===== */
.laporan-header {
  display: flex;
  flex-direction: column;
  align-items: center;
  margin-bottom: 25px;
}

.logo-section {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 16px;
}

.logo {
  width: 70px;
  height: 70px;
  object-fit: contain;
}

.company-info {
  text-align: left;
}

.company-info h1 {
  margin: 0;
  font-size: 20px;
  color: #0d6efd;
  font-weight: 700;
}

.company-info p {
  margin: 2px 0;
  font-size: 12px;
  color: #555;
}

.divider {
  border: none;
  border-top: 2px solid #0d6efd;
  width: 100%;
  margin-top: 15px;
}

/* ===== TITLE ===== */
h2 {
  text-align: center;
  color: #0d6efd;
  font-size: 18px;
  margin-bottom: 20px;
  text-transform: uppercase;
  letter-spacing: 0.5px;
}

/* ===== TABLE ===== */
table {
  width: 100%;
  border-collapse: collapse;
  font-size: 13px;
  margin-bottom: 18px;
}

th, td {
  border: 1px solid #444;
  padding: 7px 10px;
  text-align: left;
}

th {
  background: #0d6efd;
  color: #fff;
  font-weight: 600;
  font-size: 13px;
}

tr:nth-child(even) td {
  background: #f8f9fb;
}

/* ===== TOTAL BOX ===== */
.total-box {
  text-align: right;
  font-size: 14px;
  margin-top: 10px;
  margin-bottom: 40px;
  padding: 10px 14px;
  border: 1px solid #ccc;
  display: inline-block;
  border-radius: 8px;
  background: #f9fafc;
  font-weight: 600;
}

/* ===== FOOTER ===== */
footer {
  margin-top: 50px;
}

.footer-content {
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  font-size: 13px;
}

.footer-content .left {
  text-align: left;
}

.footer-content .generated {
  font-size: 11px;
  color: #888;
  margin-top: 6px;
  font-style: italic;
}

.footer-content .right {
  text-align: center;
  width: 250px;
}

.footer-content .stamp-area {
  margin: 16px 0;
  position: relative;
}

.footer-content .stamp {
  width: 100px;
  opacity: 0.8;
}

.footer-content .signature {
  margin-top: 30px;
  font-size: 13px;
}

/* ===== PRINT OPTIMIZATION ===== */
@media print {
  body {
    -webkit-print-color-adjust: exact !important;
    print-color-adjust: exact !important;
  }
  a[href]:after { content: ""; }
}

</style>
<body onload="window.print()">

  {{-- 🔹 HEADER LAPORAN --}}
  <header class="laporan-header">
    <div class="logo-section">
      <img src="{{ asset('images/logo-rentcar.png') }}" alt="Logo" class="logo">
      <div class="company-info">
        <h1>RentCar Indonesia</h1>
        <p>Jl. Anggrek No. 45, Bandung, Jawa Barat</p>
        <p>Email: support@rentcar.id | Telp: (022) 8901 2345</p>
      </div>
    </div>
    <hr class="divider">
  </header>

  {{-- 🔹 JUDUL --}}
  <h2>LAPORAN PENYEWAAN MOBIL</h2>

  {{-- 🔹 TABEL --}}
  <table>
    <thead>
      <tr>
        <th>No</th>
        <th>Nama User</th>
        <th>Mobil</th>
        <th>Tgl Sewa</th>
        <th>Tgl Selesai</th>
        <th>Total (Rp)</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
      @foreach($rentals as $rental)
      <tr>
        <td>{{ $loop->iteration }}</td>
        <td>{{ $rental->user->nama_lengkap }}</td>
        <td>{{ $rental->car->brand->nama_merek ?? '-' }} {{ $rental->car->model }}</td>
        <td>{{ $rental->tanggal_mulai }}</td>
        <td>{{ $rental->tanggal_selesai }}</td>
        <td>{{ number_format($rental->total_biaya, 0, ',', '.') }}</td>
        <td>{{ ucfirst($rental->status_rental) }}</td>
      </tr>
      @endforeach
    </tbody>
  </table>

  {{-- 🔹 TOTAL --}}
  <div class="total-box">
    <strong>Total Pendapatan:</strong> 
    Rp {{ number_format($totalPendapatan, 0, ',', '.') }}
  </div>

  {{-- 🔹 FOOTER TTD & CAP --}}
  <footer>
    <div class="footer-content">
      <div class="left">
        <p><em>Dicetak pada:</em> {{ $tanggalCetak }}</p>
        <p class="generated">Generated by RentCar Admin System</p>
      </div>
      <div class="right">
        <p>Bandung, {{ $tanggalCetak }}</p>
        <p><strong>Admin RentCar</strong></p>
        <div class="stamp-area">
          <img src="{{ asset('images/stamp.png') }}" alt="Cap Resmi" class="stamp">
        </div>
        <p class="signature">(_______________________)</p>
      </div>
    </div>
  </footer>

</body>
</html>
